### ISSUE TITLE
Add support for expressions

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/sql2cypher#10]
I'll implement more of the `expressions()` method, to support:

## Functions

- [x] Arithmetic expressions
- [x] https://neo4j.com/docs/cypher-manual/current/functions/mathematical-numeric/
- [x] https://neo4j.com/docs/cypher-manual/current/functions/mathematical-logarithmic/
- [x] https://neo4j.com/docs/cypher-manual/current/functions/mathematical-trigonometric/
- [x] https://neo4j.com/docs/cypher-manual/current/functions/string/
  - Note, there's still quite a few missing features in Cypher-DSL here
- [ ] https://neo4j.com/docs/cypher-manual/current/functions/temporal/
- [ ] https://neo4j.com/docs/cypher-manual/current/functions/temporal/duration/
- [ ] https://neo4j.com/docs/cypher-manual/current/functions/spatial/ ~(won't be available with the jOOQ Open Source edition)~
  - While the parser and `QOM` API don't have a representation for these things in the jOOQ Open Source Edition, we can specify `Settings.parseUnknownFunctions` and try to translate things from there.
- [x] https://neo4j.com/docs/cypher-manual/current/functions/scalar/

## Query syntax

- [x] `CASE` https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#query-syntax-case
  - [x] `CASE` abbreviations
  - [x] `CASE` simple
  - [x] `CASE` searched
- [ ] `EXISTS` (currently not supported in Cypher-DSL, with subqueries?)
- [ ] `COUNT` (doesn't have the exact SQL equivalent)

## Not yet possible:

- [ ] https://neo4j.com/docs/cypher-manual/current/functions/aggregating/ (still missing jOOQ `QOM` support, will implement next week)

**Comment by jexp** [comment]
Really great work on the expressions so far and the TCK works really well.

**Comment by michael-simons** [comment]
Kamino closed and cloned this issue to [neo4j/neo4j-jdbc](https://github.com/neo4j/neo4j-jdbc/issues/154)
