### ISSUE TITLE
Settle on a format.

### ISSUE THREAD

**Issue by michael-simons** [neo4j-contrib/sql2cypher#12]
I guess we all have different ideas about source code formatting (I'm team tab btw), but I have no ambition to discuss this.

Can we pick one:

* Spotless with Google
* Spotless with Palantir Google fork (nicer for Lambda, Neo4j core does this too)
* Spring format

I'm happy to set any of those up.

**Comment by lukaseder** [comment]
I don't have an opinion, just used IntelliJ's defaults (and I don't use IntelliJ often).

So please, set up any automation of your preference, probably ideally the same one as the one from cypher-dsl? Once I see more of your code, I'll also try to adapt to other coding styles that you prefer.

**Comment by jexp** [comment]
I don't have an opinion either, (except for not using the curly brace on new line format :)
Given my ADHD I also usually forget to/don't pay attention to things like formatting, so please bear with me. But happy to have a pre-commit hook for formatting.

So pick whichever you like @michael-simons and set it up and we'll follow it.

I wouldn't want to use something from Palantir though.

**Comment by michael-simons** [comment]
Done. See reasoning in the commit message.
