### ISSUE TITLE
Disable jOOQ banner + tips for the command line tool?

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/sql2cypher#13]
To use the tool, the banner and tips add to the output and would have to be filtered out.

Or put them on stderr at least.

We might also change the log-level config for the CLI to error or warn.

**Comment by michael-simons** [comment]
The jOOQ banner already only appears on stderr. 

```bash
➜  sql2cypher git:(issue/12) ✗ ./target/assembly/bin/sql2cypher 2>/dev/null 
MATCH (t:my_table)
WHERE t.a = 1
RETURN t.a, t.b
```

I don't see a reason to disable it. I'm thinking more about finally adding a Cypher-DSL banner, really ;)

**Comment by jexp** [comment]
Ok sorry seems I was confused.

**Comment by lukaseder** [comment]
> To use the tool, the banner and tips add to the output and would have to be filtered out.

Here's how: https://stackoverflow.com/q/28272284/521799
