### ISSUE TITLE
Build native images for the different OSes in the GH release actions?

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/sql2cypher#19]
Possibly:

* Linux (x86 / arm)
* Windows
* OSX (x86 / arm)

**Comment by michael-simons** [comment]
arm is only possible on GH with external runners, macOS prohibitive expensive when one picks AWS. For Linux arm I have one.

**Comment by michael-simons** [comment]
The binaries attached to https://github.com/neo4j-contrib/sql2cypher/releases/tag/early-access are binaries based on jlink, running with a stripped down JVM on the module path. Cross compilation can be achieved here as the compilation only needs the source jvm for the target OS in contrast to GraalVM, that needs it running (and glibc and all of that fancy stuff I have no clue about)
