### ISSUE TITLE
Interop via basic types to make native libraries easier?

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/sql2cypher#20]
As I would like to support a native library to integrate e.g. with JS, Python, .Net and R it would be good if the main entrypoints to the API (in and out) would limit themselves to basic types that are available in all languages and not specific to Java?

* strings, integers, booleans
* arrays, lists, maps

That possibly mirrors the options we want to provide for the CLI.

**Comment by michael-simons** [comment]
CLI can happily deal with enums. For a native library I would add a small shim for that and not dumb the config down further. The latter already has been rewritten that it only takes in the mentioned types, for similar reasons. It’s easier wrt serialisation and immutability as well.
