### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/sql2cypher#23]
It's probably not the top priority, but eventually, might be reasonable to think about integration tests, e.g. using testcontainers:
https://www.testcontainers.org/modules/databases/neo4j/

For this, it might be reasonable to compare the neo4j translated behaviour e.g. with H2?

The problems that the current test suite won't cover:

- Correct query semantics (e.g. when nesting / correlating stuff, there are always hairy edge cases)
- Data type conversion, etc.
- Other things?

**Comment by jexp** [comment]
Great idea.

Which free relational DB is best for a cleanest SQL standard? H2 / MySQL / Postgres?

**Comment by lukaseder** [comment]
I'd use H2 for this, it's become very standards compliant.

**Comment by michael-simons** [comment]
Kamino closed and cloned this issue to [neo4j/neo4j-jdbc](https://github.com/neo4j/neo4j-jdbc/issues/157)
