### ISSUE TITLE
Avoid build issues in jOOQ snapshots

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/sql2cypher#27]
Last night, I introduced a regression in the jOOQ OSS edition on github. Any builds here might have run into this problem, specifically:
https://github.com/neo4j-contrib/sql2cypher/actions/runs/3994373214/jobs/6852007782

The merits of building from the main branch of someone else's work 😅

How about I introduce a new tag that is used by this project's build?
https://github.com/jOOQ/jOOQ/releases/tag/version-3.18.0-sql2cypher

I'll update the tag whenever I add new `QOM` API that is useful for this project. That way, I can at least guarantee that particular snapshot version will build.

Actual snapshot builds would be better, of course, but that's something jOOQ doesn't offer for the Open Source Edition.

**Comment by michael-simons** [comment]
I'll adapt the builds
