### ISSUE TITLE
QOM for `Insert` or general `Query` is missing in jOOQ

### ISSUE THREAD

**Issue by michael-simons** [neo4j-contrib/sql2cypher#3]

**Comment by lukaseder** [comment]
Is this related to? https://github.com/neo4j-contrib/sql2cypher/issues/1.

It's not missing in jOOQ 3.18:
https://www.jooq.org/javadoc/dev/org.jooq/org/jooq/impl/QOM.Insert.html

But perhaps you downgraded jOOQ?

**Comment by lukaseder** [comment]
There's a part about the `QOM` API being experimental, where I'm not quite sure what to do with those top level types like `Query`, or any other type listed here:
https://blog.jooq.org/a-brief-overview-over-the-most-common-jooq-types/

As you can see, I'm not even sure how to name these types other than "most common jOOQ types". I'm not sure yet whether:

- There should be a separate `QOM` / `DSL` type or a shared one
- Accessors and mutators should be on the shared one (e.g. on `org.jooq.Select`) or not

We can already work with this `QOM` API, but this is the part that will probably break in the near future. Once this project here builds with tests, I'll make it part of jOOQ's CI/CD pipeline, to be able to proactively upgrade its logic, should jOOQ's API change.

So, in the short run, perhaps you have a specific question?

**Comment by michael-simons** [comment]
I don't know what I was thinking here… :) It works.
