### ISSUE TITLE
Add support for DML statements

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/sql2cypher#30]
Various DML statements can be translated, including:

- [ ] `INSERT`: https://neo4j.com/docs/cypher-manual/current/clauses/create/
  - [x] `INSERT .. VALUES`: `CREATE (n:Type { ... })` syntax
  - [ ] `INSERT .. SELECT`: `MATCH .. CREATE` syntax
  - [ ] `RETURNING` (Firebird, MariaDB, Oracle, PostgreSQL specific syntax to return deleted rows): `RETURN`?
  - [ ] `ON DUPLICATE KEY UPDATE` / `ON CONFLICT`: Probably using `MERGE`?
- [ ] `UPDATE`: https://neo4j.com/docs/cypher-manual/current/clauses/merge/
- [x] `DELETE`: https://neo4j.com/docs/cypher-manual/current/clauses/delete/
  - [x] `WHERE`: Translates to `WHERE`
  - [ ] `USING` (PostgreSQL specific `DELETE .. JOIN` syntax): Translates to ordinary graph declarations
  - [ ] `ORDER BY .. LIMIT` (MySQL specific syntax to limit the number of rows to be deleted): Perhaps with a subquery?
  - [ ] `RETURNING` (Firebird, MariaDB, Oracle, PostgreSQL specific syntax to return deleted rows): Perhaps with `RETURN`?

**Comment by michael-simons** [comment]
Add `truncate` in 1e45331.

**Comment by michael-simons** [comment]
Kamino closed and cloned this issue to [neo4j/neo4j-jdbc](https://github.com/neo4j/neo4j-jdbc/issues/152)
