### ISSUE TITLE
Add support for quantified comparison predicates

### ISSUE THREAD

**Issue by lukaseder** [neo4j-contrib/sql2cypher#35]
I'm currently refactoring jOOQ's internals in order to support quantified comparison predicates: https://github.com/jOOQ/jOOQ/issues/14560

The simplest forms include:

```sql
a = ANY (SELECT b FROM t)  -- equivalent to A IN (SELECT b FROM t)
a != ALL (SELECT b FROM t) -- equivalent to A NOT IN (SELECT b FROM t)
```

Less trivial forms involve:

- `<`, `<=`, `>`, and `>=`
- `LIKE`, `SIMILAR TO` and other operators (in PostgreSQL), quite useful: https://blog.jooq.org/quantified-like-any-predicates-in-jooq-3-12/
- Row value expression predicates: https://github.com/neo4j-contrib/sql2cypher/issues/31

Most of these can be emulated using `EXISTS`. jOOQ is already doing that for numerous SQL dialects that don't have full support, so this could be done in this translator as well, once we have `EXISTS` support in: https://github.com/neo4j-contrib/sql2cypher/issues/14

**Comment by michael-simons** [comment]
Kamino closed and cloned this issue to [neo4j/neo4j-jdbc](https://github.com/neo4j/neo4j-jdbc/issues/159)
