### ISSUE TITLE
Quoting / casing

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/sql2cypher#8]
In Cypher you keep the casing that you use in the statement. e.g. `unitPrice`

In SQL it depends on the dialect, some uppercase everything, some leave it, some require quotes or backticks.

It would be nice if we had a SQL dialect that's less intrusive and doesn't require so many quotes even for non-special character names.

Cypher is case sensitive for labels, rel-types and property-keys, while some SQL dialects are not.

Hmm thinking about it, perhaps it's ok to require the quotes if this transpiler has a machine-to-machine target.

**Comment by michael-simons** [comment]
The latter can be configured, via API and CLI now.

**Comment by michael-simons** [comment]
This was fixed.
